-- 004_agentic.sql: Agentic dashboard tables + column additions

-- Content generated by the AI CMO
create table public.content (
  id uuid primary key default uuid_generate_v4(),
  brand_id uuid not null references public.brands(id) on delete cascade,
  format text not null,
  title text,
  body text,
  brief jsonb,
  gate_report jsonb,
  status text default 'draft',
  skill text,
  gateway_job_id text,
  gateway_run_id text,
  metadata jsonb default '{}',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  published_at timestamptz
);

-- Chat history for AI SDK persistence
create table public.chat_messages (
  id uuid primary key default uuid_generate_v4(),
  brand_id uuid not null references public.brands(id) on delete cascade,
  role text not null,
  content text,
  tool_calls jsonb,
  metadata jsonb default '{}',
  created_at timestamptz default now()
);

-- Agent execution log (mirrors gateway but in Supabase for dashboard access)
create table public.agent_runs (
  id uuid primary key default uuid_generate_v4(),
  brand_id uuid not null references public.brands(id) on delete cascade,
  task_type text not null,
  skill text,
  trigger text not null default 'dashboard',
  status text default 'pending',
  input jsonb,
  output jsonb,
  error text,
  risk_tier text default 'low',
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz default now()
);

-- Add columns to actions
alter table public.actions add column if not exists skill text;
alter table public.actions add column if not exists gateway_job_id text;
alter table public.actions add column if not exists trigger text default 'dashboard';

-- Add columns to brands
alter table public.brands add column if not exists autonomy_mode text default 'balanced';
alter table public.brands add column if not exists gateway_url text;
alter table public.brands add column if not exists gateway_key text;

-- RLS for new tables
alter table public.content enable row level security;
alter table public.chat_messages enable row level security;
alter table public.agent_runs enable row level security;

create policy "content_select" on public.content
  for select using (brand_id in (select id from public.brands where user_id = auth.uid()));
create policy "content_insert" on public.content
  for insert with check (brand_id in (select id from public.brands where user_id = auth.uid()));
create policy "content_update" on public.content
  for update using (brand_id in (select id from public.brands where user_id = auth.uid()));

create policy "chat_messages_select" on public.chat_messages
  for select using (brand_id in (select id from public.brands where user_id = auth.uid()));
create policy "chat_messages_insert" on public.chat_messages
  for insert with check (brand_id in (select id from public.brands where user_id = auth.uid()));

create policy "agent_runs_select" on public.agent_runs
  for select using (brand_id in (select id from public.brands where user_id = auth.uid()));
create policy "agent_runs_insert" on public.agent_runs
  for insert with check (brand_id in (select id from public.brands where user_id = auth.uid()));
create policy "agent_runs_update" on public.agent_runs
  for update using (brand_id in (select id from public.brands where user_id = auth.uid()));

-- Indexes
create index idx_content_brand_id on public.content(brand_id);
create index idx_content_status on public.content(status);
create index idx_content_format on public.content(format);
create index idx_chat_brand_id on public.chat_messages(brand_id);
create index idx_agent_runs_brand_id on public.agent_runs(brand_id);
create index idx_agent_runs_status on public.agent_runs(status);

-- Updated_at triggers
create trigger content_updated_at before update on public.content
  for each row execute function update_updated_at();

-- Check constraints
alter table public.content
  add constraint valid_content_status
  check (status in ('draft', 'approved', 'published', 'rejected'));

alter table public.agent_runs
  add constraint valid_agent_run_status
  check (status in ('pending', 'running', 'completed', 'failed'));

alter table public.brands
  add constraint valid_autonomy_mode
  check (autonomy_mode in ('supervised', 'balanced', 'autonomous'));

-- Enable Realtime on new tables
alter publication supabase_realtime add table public.content;
alter publication supabase_realtime add table public.agent_runs;
