"""Social content management — content types, format rules, scheduling, captions, and automation."""

from kai.social.content_types import (
    ContentTypeTemplate,
    PlatformFormatRules,
    SocialContentType,
    SocialPlatform,
    CONTENT_TYPE_TEMPLATES,
    PLATFORM_RULES,
    get_content_type_template,
    get_platform_rules,
    get_supported_content_types,
    validate_post_for_platform,
)

from kai.social.caption_engine import (
    CaptionGenerator,
    CaptionRequest,
    CaptionResult,
    GeoTagRecommendation,
    GeoTagRecommender,
    HashtagGenerator,
    HashtagSet,
    HashtagStrategy,
    HOOK_TEMPLATES,
    CTA_LIBRARY,
    INDUSTRY_HASHTAG_MAP,
)

from kai.social.proof_of_life import (
    ContentInventoryItem,
    FillerCheckResult,
    FillerRejectionReason,
    FillerSuppressor,
    PlatformHealth,
    ProofOfLifeEngine,
    ProofOfLifePlan,
    ProofOfLifeStatus,
    StalenessAlert,
    StalenessDetector,
    GENERIC_MOTIVATIONAL_PATTERNS,
    EMPTY_HOLIDAY_PATTERNS,
    generate_stale_alert_id,
    days_between,
    get_current_season,
    is_seasonal_relevant,
)

__all__ = [
    # content_types
    "ContentTypeTemplate",
    "PlatformFormatRules",
    "SocialContentType",
    "SocialPlatform",
    "CONTENT_TYPE_TEMPLATES",
    "PLATFORM_RULES",
    "get_content_type_template",
    "get_platform_rules",
    "get_supported_content_types",
    "validate_post_for_platform",
    # caption_engine
    "CaptionGenerator",
    "CaptionRequest",
    "CaptionResult",
    "GeoTagRecommendation",
    "GeoTagRecommender",
    "HashtagGenerator",
    "HashtagSet",
    "HashtagStrategy",
    "HOOK_TEMPLATES",
    "CTA_LIBRARY",
    "INDUSTRY_HASHTAG_MAP",
    # proof_of_life
    "ContentInventoryItem",
    "FillerCheckResult",
    "FillerRejectionReason",
    "FillerSuppressor",
    "PlatformHealth",
    "ProofOfLifeEngine",
    "ProofOfLifePlan",
    "ProofOfLifeStatus",
    "StalenessAlert",
    "StalenessDetector",
    "GENERIC_MOTIVATIONAL_PATTERNS",
    "EMPTY_HOLIDAY_PATTERNS",
    "generate_stale_alert_id",
    "days_between",
    "get_current_season",
    "is_seasonal_relevant",
]
